### ISSUE TITLE
Can I use this instead of @typicode's hotel?

### ISSUE THREAD

**Issue by shreyasminocha** [luisfarzati/localdots#3]
I want to run services by invoking CLI commands like [hotel](https://github.com/typicode/hotel#popular-servers-examples) allows me to. Can I use localdots to do this?

**Comment by lufzle** [comment]
Hi @shreyasminocha, no, localdots doesn't have a CLI. It is meant to be used as a background service. It's really nothing else than a Caddy proxy server with a few automated helpers for convenience.

**Comment by lufzle** [comment]
Having said that, I'm open to suggestions for CLI or programmatic extensions. Just feel free to propose. :)
